columns:
  fixed acidity: float64
  volatile acidity: float64
  citric acid: float64
  residual sugar: float64
  chlorides: float64
  free sulphur dioxide: float64
  total sulphur dioxide: float64
  density: float64
  pH: float64
  sulphates: float64
  alchohol: float64
  quality: int64
  id: int64

target_column:
  name: quality
  
